# Generated by Django 4.0.1 on 2022-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
